# Target branch configuration
[branches] # If no other configuration is found, the default branch will be used
default = "develop"

[branches.includes] # If the branch name includes the word "hotfix", the target branch will be "main"
# You can add other rules with the same logic, for example:
# If the branch name includes the word "feature", the target branch will be "develop"
hotfix = "main"

[title] # By default the PR title with be the branch name, changed from kebab case to title case e.g. branch-1234-my-ticket-name -> Branch 1234 My Ticket Name

[title.jira_prefixes] # This is the project prefix on jira, {ticket_number} and {ticket_name} will be replaced with the ticket number and name if using the jira branch naming convention
htp20 = "[HTP20-{ticket_number}] {ticket_name}" # e.g. "HTP20-1234 My ticket name"

[title.prefixes] # This will replace the prefix used with a given prefix
hotfix = "Hotfix:"


[template] # Absolute path to the template file
path = "/Users/fernandosobral/scripts/ghpr-script/src/template.md"

[labels]
default = ["draft"] # All branches will be assigned the default labels

[labels.includes] # If the branch name includes the word "hotfix", the labels will also include "hotfix"
hotfix = ["hotfix"]


[commits] # How your commits will be formatted on the PR
# If the commit message starts with "feat:", the PR will be prefixed with the text ""
# If the commit message starts with "fix:", the PR will be assigned the label "Fix: "
[commits.prefixes] # Prefixes are assumed to end on : or (scope): as per https://www.conventionalcommits.org/en/v1.0.0/#specification
feat = ""
fix = "Fix:"
chore = "Chore:"


[draft]
default = false # For this to work draft pr must be enabled on the repo
